#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    FILE_PATH="$1"
    SERVER_IP="$2"
    USERNAME="$3"
    SSH_KEY="$4"

    # Transfer the file to the user's home directory on the server
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
fi
