#!/usr/bin/env bash

# Configures Nginx to redirect /redirect_me to another page with a 301 Moved Permanently

# Update and install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

# Set up redirection configuration
echo -e "\nConfiguring redirection.\n"

sudo bash -c 'cat << EOF > /etc/nginx/sites-available/redirect
server {
    listen 80;
    listen [::]:80;
    server_name _;

    # Redirect /redirect_me to another page with a 301 Moved Permanently
    location /redirect_me {
        return 301 https://example.com/redirected_page;
    }

    # Serve a default Hello World page
    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF'

# Enable the redirection site configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test Nginx configuration and restart
echo -e "\nTesting Nginx configuration and restarting Nginx.\n"
sudo nginx -t && sudo service nginx restart

echo -e "\nRedirection configuration completed. ✅\n"
