#!/usr/bin/env bash

# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

# Updates the package lists for available software packages.
sudo apt-get update -y
# Installs the Nginx web server.
sudo apt-get install -y nginx

# Creates the /etc/nginx/html directory, which will serve as the document root directory for Nginx.
sudo mkdir -p /etc/nginx/html
# Creates an empty index.html file inside the /etc/nginx/html directory.
sudo touch /etc/nginx/html/index.html
# Sets the content of the index.html file to "Hello World!" using the echo command.
echo "Hello World!" | sudo tee /etc/nginx/html/index.html >/dev/null
# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
sudo printf "%s" "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" | sudo tee /etc/nginx/sites-available/default >/dev/null

# Configure a new server block for redirection
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/redirect
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Enable the new site configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
