#!/usr/bin/env bash

# Update package repository and install Nginx
apt-get update -y
apt-get install nginx -y

# Define the custom header string
header_string="add_header X-Served-By \$hostname;"

# Add the custom header configuration to Nginx default site configuration
echo "Configuring Nginx..."
sed -i "s/# server_tokens off;/# server_tokens off;\n\t$header_string/" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
service nginx restart

echo "Nginx configured successfully with custom HTTP response header."